import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const maglony = localFont({
  src: "../../public/fonts/Maglony.ttf",
  variable: "--maglony",
});
const clashGrotesk = localFont({
  src: "../../public/fonts/ClashGrotesk.ttf",
  variable: "--clashGrotesk",
});
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--spaceGrotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${maglony.variable} ${clashGrotesk.variable} font-clashGrotesk bg-[#EAEAEA]`}
      >
        {children}
      </body>
    </html>
  );
}
